### ISSUE TITLE
Failed to minify Metadata.js when building app

### ISSUE THREAD

**Issue by Tetraib** [Baqend/react-redux-starter#1]
Hi,
For evaluation purpose I tried to build the application and it showed the following error 

> Failed to minify the code from this file:
> ./node_modules/baqend/lib/util/Metadata.js:12

Apparently it doesn't affect the produced application.

**Comment by kddc** [comment]
Hi,
Thank you for pointing this out. We already updated the repository. The problem was that we loaded our baqend library from sources, which is considered bad practice in Create-React-App [Link](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). Just change `import { db } from 'baqend/lib/baqend'` to `import { db } from 'baqend'` in all your application sources (`store.js` and `Messages.js` in the starter) and it will work again.
